### 식품영양분DB정보

In [1]:
import pandas as pd

In [17]:
path = '../data/식품영양성분DB정보.csv'
df = pd.read_csv(path, encoding='utf-8', low_memory=False)

In [19]:
# 기본구조
df.shape

(167548, 193)

In [61]:
for col, dtype in zip(df.columns, df.dtypes):
    print(f"{col}: {dtype}")

NUM: int64
FOOD_CD: object
FOOD_NM_KR: object
DB_GRP_CM: object
DB_GRP_NM: object
DB_CLASS_CM: int64
DB_CLASS_NM: object
FOOD_OR_CD: int64
FOOD_OR_NM: object
FOOD_CAT1_CD: int64
FOOD_CAT1_NM: object
FOOD_REF_CD: int64
FOOD_REF_NM: object
FOOD_CAT2_CD: float64
FOOD_CAT2_NM: object
FOOD_CAT3_CD: float64
FOOD_CAT3_NM: object
FOOD_CAT4_CD: float64
FOOD_CAT4_NM: object
SERVING_SIZE: object
AMT_NUM1: object
AMT_NUM2: float64
AMT_NUM3: object
AMT_NUM4: object
AMT_NUM5: float64
AMT_NUM6: object
AMT_NUM7: object
AMT_NUM8: float64
AMT_NUM9: object
AMT_NUM10: float64
AMT_NUM11: object
AMT_NUM12: object
AMT_NUM13: object
AMT_NUM14: object
AMT_NUM15: object
AMT_NUM16: object
AMT_NUM17: object
AMT_NUM18: object
AMT_NUM19: float64
AMT_NUM20: object
AMT_NUM21: object
AMT_NUM22: object
AMT_NUM23: object
AMT_NUM24: float64
AMT_NUM25: float64
AMT_NUM26: float64
AMT_NUM27: float64
AMT_NUM28: object
AMT_NUM29: float64
AMT_NUM30: object
AMT_NUM31: object
AMT_NUM32: float64
AMT_NUM33: object
AMT_NUM34: float64
AMT_NUM35: object
AMT_NUM36: object
AMT_NUM37: float64
AMT_NUM38: float64
AMT_NUM39: float64
AMT_NUM40: float64
AMT_NUM41: float64
AMT_NUM42: float64
AMT_NUM43: float64
AMT_NUM44: float64
AMT_NUM45: float64
AMT_NUM46: float64
AMT_NUM47: float64
AMT_NUM48: object
AMT_NUM49: object
AMT_NUM50: object
AMT_NUM51: float64
AMT_NUM52: float64
AMT_NUM53: float64
AMT_NUM54: float64
AMT_NUM55: float64
AMT_NUM56: float64
AMT_NUM57: float64
AMT_NUM58: float64
AMT_NUM59: float64
AMT_NUM60: float64
AMT_NUM61: float64
AMT_NUM62: object
AMT_NUM63: object
AMT_NUM64: float64
AMT_NUM65: float64
AMT_NUM66: float64
AMT_NUM67: object
AMT_NUM68: float64
AMT_NUM69: object
AMT_NUM70: object
AMT_NUM71: float64
AMT_NUM72: object
AMT_NUM73: float64
AMT_NUM74: object
AMT_NUM75: float64
AMT_NUM76: object
AMT_NUM77: object
AMT_NUM78: object
AMT_NUM79: object
AMT_NUM80: object
AMT_NUM81: object
AMT_NUM82: float64
AMT_NUM83: object
AMT_NUM84: object
AMT_NUM85: float64
AMT_NUM86: float64
AMT_NUM87: object
AMT_NUM88: float64
AMT_NUM89: float64
AMT_NUM90: object
AMT_NUM91: float64
AMT_NUM92: float64
AMT_NUM93: object
AMT_NUM94: object
AMT_NUM95: object
AMT_NUM96: object
AMT_NUM97: float64
AMT_NUM98: object
AMT_NUM99: object
AMT_NUM100: float64
AMT_NUM101: object
AMT_NUM102: object
AMT_NUM103: object
AMT_NUM104: object
AMT_NUM105: object
AMT_NUM106: float64
AMT_NUM107: object
AMT_NUM108: float64
AMT_NUM109: float64
AMT_NUM110: object
AMT_NUM111: object
AMT_NUM112: float64
AMT_NUM113: float64
AMT_NUM114: float64
AMT_NUM115: object
AMT_NUM116: object
AMT_NUM117: float64
AMT_NUM118: object
AMT_NUM119: object
AMT_NUM120: object
AMT_NUM121: object
AMT_NUM122: float64
AMT_NUM123: object
AMT_NUM124: object
AMT_NUM125: object
AMT_NUM126: object
AMT_NUM127: object
AMT_NUM128: object
AMT_NUM129: object
AMT_NUM130: object
AMT_NUM131: object
AMT_NUM132: object
AMT_NUM133: object
AMT_NUM134: object
AMT_NUM135: object
AMT_NUM136: object
AMT_NUM137: object
AMT_NUM138: object
AMT_NUM139: object
AMT_NUM140: object
AMT_NUM141: object
AMT_NUM142: float64
AMT_NUM143: float64
AMT_NUM144: float64
AMT_NUM145: float64
AMT_NUM146: float64
AMT_NUM147: float64
AMT_NUM148: float64
AMT_NUM149: object
AMT_NUM150: float64
AMT_NUM151: float64
AMT_NUM152: float64
AMT_NUM153: object
AMT_NUM154: float64
AMT_NUM155: float64
AMT_NUM156: float64
AMT_NUM157: float64
SUB_REF_CM: int64
SUB_REF_NAME: object
NUTRI_AMOUNT_SERVING: object
Z10500: object
DISH_ONE_SERVING: float64
ITEM_REPORT_NO: object
MAKER_NM: object
IMP_MANUFAC_NM: object
SELLER_MANUFAC_NM: object
IMP_YN: object
NATION_CM: object
NATION_NM: object
CRT_MTH_CD: float64
CRT_MTH_NM: object
RESEARCH_YMD: object
UPDATE_DATE: object

In [29]:
df.head()

,NUM,FOOD_CD,FOOD_NM_KR,DB_GRP_CM,DB_GRP_NM,DB_CLASS_CM,DB_CLASS_NM,FOOD_OR_CD,FOOD_OR_NM,FOOD_CAT1_CD,...,MAKER_NM,IMP_MANUFAC_NM,SELLER_MANUFAC_NM,IMP_YN,NATION_CM,NATION_NM,CRT_MTH_CD,CRT_MTH_NM,RESEARCH_YMD,UPDATE_DATE
0,1,D101-004160000-0001,국밥_돼지머리,D,음식,1,품목대표,1,가정식(분석 함량),1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,분석,2017-12-31,2025-01-23
1,2,D101-004310000-0001,국밥_순대국밥,D,음식,1,품목대표,1,가정식(분석 함량),1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,분석,2017-12-31,2025-01-23
2,3,D101-004500000-0001,국밥_콩나물,D,음식,1,품목대표,1,가정식(분석 함량),1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,분석,2018-12-31,2025-01-23
3,4,D101-006000000-0001,기장밥,D,음식,1,품목대표,1,가정식(분석 함량),1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,분석,2017-12-31,2025-01-23
4,5,D101-007000000-0001,김밥,D,음식,1,품목대표,1,가정식(분석 함량),1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,분석,2018-12-31,2025-01-23

In [63]:
for col, nul_num in zip(df.columns,df.isnull().sum()):
    print(f"{col}: {nul_num}")

NUM: 0
FOOD_CD: 0
FOOD_NM_KR: 0
DB_GRP_CM: 0
DB_GRP_NM: 0
DB_CLASS_CM: 0
DB_CLASS_NM: 0
FOOD_OR_CD: 0
FOOD_OR_NM: 0
FOOD_CAT1_CD: 0
FOOD_CAT1_NM: 193
FOOD_REF_CD: 0
FOOD_REF_NM: 116
FOOD_CAT2_CD: 2
FOOD_CAT2_NM: 310
FOOD_CAT3_CD: 2
FOOD_CAT3_NM: 450
FOOD_CAT4_CD: 1019
FOOD_CAT4_NM: 1496
SERVING_SIZE: 1
AMT_NUM1: 103
AMT_NUM2: 158384
AMT_NUM3: 117
AMT_NUM4: 9208
AMT_NUM5: 161585
AMT_NUM6: 8707
AMT_NUM7: 2564
AMT_NUM8: 157379
AMT_NUM9: 156081
AMT_NUM10: 157569
AMT_NUM11: 159008
AMT_NUM12: 158801
AMT_NUM13: 1628
AMT_NUM14: 162611
AMT_NUM15: 164425
AMT_NUM16: 159608
AMT_NUM17: 160083
AMT_NUM18: 158990
AMT_NUM19: 158657
AMT_NUM20: 158903
AMT_NUM21: 158124
AMT_NUM22: 159954
AMT_NUM23: 11671
AMT_NUM24: 2612
AMT_NUM25: 15237
AMT_NUM26: 165943
AMT_NUM27: 165941
AMT_NUM28: 165528
AMT_NUM29: 165759
AMT_NUM30: 164468
AMT_NUM31: 163819
AMT_NUM32: 167543
AMT_NUM33: 165167
AMT_NUM34: 165771
AMT_NUM35: 165691
AMT_NUM36: 164574
AMT_NUM37: 165402
AMT_NUM38: 166804
AMT_NUM39: 165403
AMT_NUM40: 165496
AMT_NUM41: 165496
AMT_NUM42: 165496
AMT_NUM43: 166804
AMT_NUM44: 165712
AMT_NUM45: 165712
AMT_NUM46: 165711
AMT_NUM47: 165713
AMT_NUM48: 165771
AMT_NUM49: 165631
AMT_NUM50: 166010
AMT_NUM51: 165694
AMT_NUM52: 164904
AMT_NUM53: 167302
AMT_NUM54: 164905
AMT_NUM55: 166955
AMT_NUM56: 166937
AMT_NUM57: 164870
AMT_NUM58: 164902
AMT_NUM59: 167544
AMT_NUM60: 164902
AMT_NUM61: 165323
AMT_NUM62: 167526
AMT_NUM63: 162009
AMT_NUM64: 161612
AMT_NUM65: 162935
AMT_NUM66: 162978
AMT_NUM67: 161434
AMT_NUM68: 167448
AMT_NUM69: 161430
AMT_NUM70: 165588
AMT_NUM71: 167448
AMT_NUM72: 161416
AMT_NUM73: 162936
AMT_NUM74: 161543
AMT_NUM75: 167548
AMT_NUM76: 161554
AMT_NUM77: 161382
AMT_NUM78: 164888
AMT_NUM79: 162906
AMT_NUM80: 164814
AMT_NUM81: 161377
AMT_NUM82: 164908
AMT_NUM83: 161597
AMT_NUM84: 161545
AMT_NUM85: 161523
AMT_NUM86: 167548
AMT_NUM87: 162759
AMT_NUM88: 161558
AMT_NUM89: 164839
AMT_NUM90: 161425
AMT_NUM91: 163011
AMT_NUM92: 163017
AMT_NUM93: 161747
AMT_NUM94: 164812
AMT_NUM95: 161521
AMT_NUM96: 164808
AMT_NUM97: 165619
AMT_NUM98: 165006
AMT_NUM99: 165006
AMT_NUM100: 165202
AMT_NUM101: 165006
AMT_NUM102: 165646
AMT_NUM103: 161386
AMT_NUM104: 161376
AMT_NUM105: 165433
AMT_NUM106: 165646
AMT_NUM107: 165447
AMT_NUM108: 165432
AMT_NUM109: 167548
AMT_NUM110: 164525
AMT_NUM111: 161869
AMT_NUM112: 164550
AMT_NUM113: 165625
AMT_NUM114: 167546
AMT_NUM115: 164650
AMT_NUM116: 161408
AMT_NUM117: 167533
AMT_NUM118: 165626
AMT_NUM119: 167507
AMT_NUM120: 164933
AMT_NUM121: 165416
AMT_NUM122: 167544
AMT_NUM123: 164681
AMT_NUM124: 164682
AMT_NUM125: 164634
AMT_NUM126: 164630
AMT_NUM127: 164638
AMT_NUM128: 164632
AMT_NUM129: 164681
AMT_NUM130: 164696
AMT_NUM131: 164632
AMT_NUM132: 164681
AMT_NUM133: 164681
AMT_NUM134: 164633
AMT_NUM135: 166128
AMT_NUM136: 164636
AMT_NUM137: 165509
AMT_NUM138: 164782
AMT_NUM139: 164635
AMT_NUM140: 164682
AMT_NUM141: 164649
AMT_NUM142: 167448
AMT_NUM143: 167448
AMT_NUM144: 167448
AMT_NUM145: 165568
AMT_NUM146: 165720
AMT_NUM147: 165720
AMT_NUM148: 165795
AMT_NUM149: 165321
AMT_NUM150: 165771
AMT_NUM151: 165465
AMT_NUM152: 165251
AMT_NUM153: 165251
AMT_NUM154: 165346
AMT_NUM155: 167448
AMT_NUM156: 164682
AMT_NUM157: 164462
SUB_REF_CM: 0
SUB_REF_NAME: 0
NUTRI_AMOUNT_SERVING: 41908
Z10500: 5383
DISH_ONE_SERVING: 167548
ITEM_REPORT_NO: 31400
MAKER_NM: 18031
IMP_MANUFAC_NM: 158367
SELLER_MANUFAC_NM: 161472
IMP_YN: 17976
NATION_CM: 163619
NATION_NM: 165740
CRT_MTH_CD: 296
CRT_MTH_NM: 296
RESEARCH_YMD: 0
UPDATE_DATE: 0

In [35]:
df.duplicated().sum()

0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167548 entries, 0 to 167547
Columns: 193 entries, NUM to UPDATE_DATE
dtypes: float64(77), int64(6), object(110)
memory usage: 246.7+ MB

In [26]:
pd.set_option('display.max_rows', 200)  # 출력할 최대 행 수 늘리기 (기본은 10)
pd.set_option('display.max_columns', 200)  # 컬럼 수 제한 해제
pd.set_option('display.max_colwidth', None)  # 컬럼 내용 길이 제한 없음
pd.set_option('display.width', None)  # 줄 바꿈 없이 전체 출력

# 결측치 전체 출력
print(df.isnull().sum())

NUM                          0
FOOD_CD                      0
FOOD_NM_KR                   0
DB_GRP_CM                    0
DB_GRP_NM                    0
DB_CLASS_CM                  0
DB_CLASS_NM                  0
FOOD_OR_CD                   0
FOOD_OR_NM                   0
FOOD_CAT1_CD                 0
FOOD_CAT1_NM               193
FOOD_REF_CD                  0
FOOD_REF_NM                116
FOOD_CAT2_CD                 2
FOOD_CAT2_NM               310
FOOD_CAT3_CD                 2
FOOD_CAT3_NM               450
FOOD_CAT4_CD              1019
FOOD_CAT4_NM              1496
SERVING_SIZE                 1
AMT_NUM1                   103
AMT_NUM2                158384
AMT_NUM3                   117
AMT_NUM4                  9208
AMT_NUM5                161585
AMT_NUM6                  8707
AMT_NUM7                  2564
AMT_NUM8                157379
AMT_NUM9                156081
AMT_NUM10               157569
AMT_NUM11               159008
AMT_NUM12               158801
AMT_NUM13                 1628
AMT_NUM14               162611
AMT_NUM15               164425
AMT_NUM16               159608
AMT_NUM17               160083
AMT_NUM18               158990
AMT_NUM19               158657
AMT_NUM20               158903
AMT_NUM21               158124
AMT_NUM22               159954
AMT_NUM23                11671
AMT_NUM24                 2612
AMT_NUM25                15237
AMT_NUM26               165943
AMT_NUM27               165941
AMT_NUM28               165528
AMT_NUM29               165759
AMT_NUM30               164468
AMT_NUM31               163819
AMT_NUM32               167543
AMT_NUM33               165167
AMT_NUM34               165771
AMT_NUM35               165691
AMT_NUM36               164574
AMT_NUM37               165402
AMT_NUM38               166804
AMT_NUM39               165403
AMT_NUM40               165496
AMT_NUM41               165496
AMT_NUM42               165496
AMT_NUM43               166804
AMT_NUM44               165712
AMT_NUM45               165712
AMT_NUM46               165711
AMT_NUM47               165713
AMT_NUM48               165771
AMT_NUM49               165631
AMT_NUM50               166010
AMT_NUM51               165694
AMT_NUM52               164904
AMT_NUM53               167302
AMT_NUM54               164905
AMT_NUM55               166955
AMT_NUM56               166937
AMT_NUM57               164870
AMT_NUM58               164902
AMT_NUM59               167544
AMT_NUM60               164902
AMT_NUM61               165323
AMT_NUM62               167526
AMT_NUM63               162009
AMT_NUM64               161612
AMT_NUM65               162935
AMT_NUM66               162978
AMT_NUM67               161434
AMT_NUM68               167448
AMT_NUM69               161430
AMT_NUM70               165588
AMT_NUM71               167448
AMT_NUM72               161416
AMT_NUM73               162936
AMT_NUM74               161543
AMT_NUM75               167548
AMT_NUM76               161554
AMT_NUM77               161382
AMT_NUM78               164888
AMT_NUM79               162906
AMT_NUM80               164814
AMT_NUM81               161377
AMT_NUM82               164908
AMT_NUM83               161597
AMT_NUM84               161545
AMT_NUM85               161523
AMT_NUM86               167548
AMT_NUM87               162759
AMT_NUM88               161558
AMT_NUM89               164839
AMT_NUM90               161425
AMT_NUM91               163011
AMT_NUM92               163017
AMT_NUM93               161747
AMT_NUM94               164812
AMT_NUM95               161521
AMT_NUM96               164808
AMT_NUM97               165619
AMT_NUM98               165006
AMT_NUM99               165006
AMT_NUM100              165202
AMT_NUM101              165006
AMT_NUM102              165646
AMT_NUM103              161386
AMT_NUM104              161376
AMT_NUM105              165433
AMT_NUM106              165646
AMT_NUM107              165447
AMT_NUM108              165432
AMT_NUM109              167548
AMT_NUM110              164525
AMT_NUM111              161869
AMT_NUM112              164550
AMT_NUM113              165625
AMT_NUM114              167546
AMT_NUM115              164650
AMT_NUM116              161408
AMT_NUM117              167533
AMT_NUM118              165626
AMT_NUM119              167507
AMT_NUM120              164933
AMT_NUM121              165416
AMT_NUM122              167544
AMT_NUM123              164681
AMT_NUM124              164682
AMT_NUM125              164634
AMT_NUM126              164630
AMT_NUM127              164638
AMT_NUM128              164632
AMT_NUM129              164681
AMT_NUM130              164696
AMT_NUM131              164632
AMT_NUM132              164681
AMT_NUM133              164681
AMT_NUM134              164633
AMT_NUM135              166128
AMT_NUM136              164636
AMT_NUM137              165509
AMT_NUM138              164782
AMT_NUM139              164635
AMT_NUM140              164682
AMT_NUM141              164649
AMT_NUM142              167448
AMT_NUM143              167448
AMT_NUM144              167448
AMT_NUM145              165568
AMT_NUM146              165720
AMT_NUM147              165720
AMT_NUM148              165795
AMT_NUM149              165321
AMT_NUM150              165771
AMT_NUM151              165465
AMT_NUM152              165251
AMT_NUM153              165251
AMT_NUM154              165346
AMT_NUM155              167448
AMT_NUM156              164682
AMT_NUM157              164462
SUB_REF_CM                   0
SUB_REF_NAME                 0
NUTRI_AMOUNT_SERVING     41908
Z10500                    5383
DISH_ONE_SERVING        167548
ITEM_REPORT_NO           31400
MAKER_NM                 18031
IMP_MANUFAC_NM          158367
SELLER_MANUFAC_NM       161472
IMP_YN                   17976
NATION_CM               163619
NATION_NM               165740
CRT_MTH_CD                 296
CRT_MTH_NM                 296
RESEARCH_YMD                 0
UPDATE_DATE                  0
dtype: int64

In [30]:
print("고유 식품 수:", df['FOOD_NM_KR'].nunique())

고유 식품 수: 148219

### 전처리

In [103]:
import pandas as pd

# ----------------------------
# 1. CSV 로드 (한글 인코딩 주의)
# ----------------------------
df = pd.read_csv('../data/식품영양성분DB정보.csv', encoding='utf-8-sig', low_memory=False)

# ----------------------------
# 2. 추출할 컬럼 정의 및 컬럼명 매핑
# ----------------------------
col_map = {
    'FOOD_CD': 'food_code',
    'FOOD_NM_KR': 'food_name',
    'SERVING_SIZE': 'serving_size(g)',
    'Z10500':'net_weight(g)',
    'AMT_NUM1': 'calorie_kcal',
    'AMT_NUM3': 'protein_g',
    'AMT_NUM4': 'fat_g',
    'AMT_NUM6': 'carbohydrate_g',
    'AMT_NUM7': 'sugar_g',
    'AMT_NUM13': 'sodium_mg',
    'AMT_NUM14': 'vitamin_a_μg',
    'AMT_NUM21': 'vitamin_c_mg',
    'AMT_NUM22': 'vitamin_d_mg',
    'AMT_NUM23': 'cholesterol_mg',
    'AMT_NUM24': 'saturated_fat_g',
    'AMT_NUM25': 'trans_fat_g',
    'AMT_NUM30': 'vitamin_b12_μg',
    'AMT_NUM116': 'zinc_mg',
    
}

df_nutr = df[list(col_map.keys())].rename(columns=col_map)
df_nutr['serving_size(g)'] = df_nutr['serving_size(g)'].str.extract(r'(\d+\.?\d*)').astype(float)
df_nutr['net_weight(g)'] = df_nutr['net_weight(g)'].str.extract(r'(\d+\.?\d*)').astype(float)


# ----------------------------
# 3. 숫자형 컬럼 변환 (문자 → float64)
# ----------------------------
numeric_cols = list(col_map.values())[2:]  # serving_size부터 끝까지
df_nutr[numeric_cols] = df_nutr[numeric_cols].apply(pd.to_numeric, errors='coerce')

# ----------------------------
# 4. 주요 성분 결측 제거
# ----------------------------
key_cols = ['calorie_kcal', 'carbohydrate_g', 'protein_g', 'fat_g']
df_nutr = df_nutr.dropna(subset=key_cols, how='any')

# ----------------------------
# 5. 중복 제거 (식품명 기준)
# ----------------------------
df_nutr = df_nutr.drop_duplicates(subset='food_name')

# ----------------------------
# 6. 저장
# ----------------------------
df_nutr.to_csv('../data_preprocessing/식품영양성분DB_전처리.csv', index=False, encoding='utf-8-sig')
print("전처리 완료: '../data_preprocessing/식품영양성분DB_전처리.csv'")

전처리 완료: '../data_preprocessing/식품영양성분DB_전처리.csv'